import type { FeatureDefinition } from './featureRegistry';

export const FEATURE_REGISTRY: Record<string, FeatureDefinition> = {
    JOBFIT: {
        id: 'jobfit',
        key: 'JOBFIT',
        name: 'AI Job Analysis',
        shortName: 'Match',
        releaseDate: '2024-11-01', // No longer "New"
        description: {
            short: 'Instant 0–100 compatibility rating.',
            full: 'Instant 0–100 compatibility rating. Get a detailed analysis of how your profile fits any job posting.',
            plan: 'Simple match quality ratings for every role',
        },
        action: { short: 'View Match', full: 'View Match' },
        iconName: 'Sparkles',
        colorKey: 'indigo',
        category: 'JOB',
        tier: 'explorer',
        targetView: 'job-match',
        link: '/jobs/match',
        rank: 1,
        showOnHomepage: true,
        planHighlight: true,
    },
    AI_SAFETY: {
        id: 'ai-safety',
        key: 'AI_SAFETY',
        name: 'AI Safety Scan',
        shortName: 'Safety',
        description: {
            short: 'Flags AI-banned postings automatically.',
            full: 'Navigator automatically flags job postings that actively ban AI-assisted applications so you know before you even decide to apply.',
            plan: 'Automatic AI-ban detection on job postings',
        },
        action: { short: 'Scan', full: 'Scan' },
        iconName: 'Shield',
        colorKey: 'amber',
        category: 'JOB',
        tier: 'plus',
        targetView: 'job-home',
        link: '/jobs',
        releaseDate: '2024-11-15',
        rank: 15,
    },
    RESUME_TAILORING: {
        id: 'resume-tailoring',
        key: 'RESUME_TAILORING',
        name: 'Resume Tailoring',
        shortName: 'Tailor',
        description: {
            short: 'One-click bullet rewrites for any job.',
            full: "Rewrite your resume bullets to match a job's exact keywords and requirements. Just pick a block and tailor it in one click.",
            plan: 'AI-powered resume bullet rewrites per job',
        },
        action: { short: 'Tailor', full: 'Tailor' },
        iconName: 'RefreshCw',
        colorKey: 'rose',
        category: 'JOB',
        tier: 'plus',
        targetView: 'resumes',
        link: '/jobs/resumes',
        releaseDate: '2024-12-15',
        rank: 14,
    },
    KEYWORDS: {
        id: 'keywords',
        key: 'KEYWORDS',
        name: 'Skills Gap Analysis',
        shortName: 'Skills',
        description: {
            short: 'Identify missing skills to beat the ATS.',
            full: "Identify exactly which skills you're missing for a specific role and close the gap before you apply.",
            plan: 'Identify and bridge missing keywords',
        },
        action: { short: 'Audit gaps', full: 'Audit' },
        iconName: 'Zap',
        colorKey: 'sky',
        category: 'COACH',
        tier: 'plus',
        targetView: 'skills',
        link: '/career/skills',
        rank: 3,
        showOnHomepage: false,
        planHighlight: true,
    },
    RESUMES: {
        id: 'resumes',
        key: 'RESUMES',
        name: 'Resume Profiles',
        shortName: 'Resume',
        description: {
            short: 'Tailored summaries for every application.',
            full: 'Manage multiple resume versions tailored to different roles. Switch between them instantly as you apply.',
            plan: 'Multiple resume versions for different roles',
        },
        action: { short: 'Manage', full: 'Manage' },
        iconName: 'FileText',
        colorKey: 'rose',
        category: 'JOB',
        tier: 'explorer',
        targetView: 'resumes',
        link: '/jobs/resumes',
        rank: 5,
        showOnHomepage: true,
    },
    COVER_LETTERS: {
        id: 'cover_letters',
        key: 'COVER_LETTERS',
        name: 'Cover Letters',
        shortName: 'Cover Letters',
        description: {
            short: 'Generate persuasive cover letters instantly.',
            full: 'Generate polished cover letters built from your real experience and the specific requirements of the job.',
            plan: 'AI-generated cover letters from your experience',
        },
        action: { short: 'Create', full: 'Write' },
        iconName: 'PenTool',
        colorKey: 'violet',
        category: 'JOB',
        tier: 'plus',
        targetView: 'cover-letters',
        link: '/jobs/cover-letters',
        rank: 2,
        showOnHomepage: true,
        planHighlight: true,
        releaseDate: '2025-01-10',
    },
    RESUME_INTERVIEW: {
        id: 'resume-interview',
        key: 'RESUME_INTERVIEW',
        name: 'Resume Interview',
        shortName: 'Story Mode',
        description: {
            short: 'Capture the real story behind your resume.',
            full: 'Answer a few focused questions about each experience block. The depth you reveal gets woven automatically into every cover letter you generate.',
            plan: 'Narrative context capture for stronger cover letters',
        },
        action: { short: 'Tell Your Story', full: 'Tell Your Story' },
        iconName: 'BookOpen',
        colorKey: 'indigo',
        category: 'JOB',
        tier: 'pro',
        targetView: 'resumes',
        link: '/jobs/resumes',
        rank: 13,
        planHighlight: true,
        stage: 'beta',
    },
    QUALITY_LOOP: {
        id: 'quality-loop',
        key: 'QUALITY_LOOP',
        name: 'Quality Loop',
        shortName: 'Quality Loop',
        description: {
            short: 'Multi-pass cover letter refinement.',
            full: "A simulated hiring manager reads, scores, and rewrites your cover letter — running up to 3 revision passes until it's ready to send.",
            plan: 'Multi-pass cover letter revision engine',
        },
        action: { short: 'Refine', full: 'Refine' },
        iconName: 'RefreshCw',
        colorKey: 'violet',
        category: 'JOB',
        tier: 'pro',
        targetView: 'cover-letters',
        link: '/jobs/cover-letters',
        rank: 16,
    },
    HISTORY: {
        id: 'history',
        key: 'HISTORY',
        name: 'Application Tracker',
        shortName: 'History',
        description: {
            short: 'Save jobs from any site with one click.',
            full: 'Keep tabs on every job you saves. Track your application status and review past results effortlessly.',
            plan: 'Unlimited saving & tracking of roles',
        },
        action: { short: 'View all', full: 'View all' },
        iconName: 'Bookmark',
        colorKey: 'blue',
        category: 'JOB',
        tier: 'explorer',
        targetView: 'history',
        link: '/jobs/history',
        rank: 6,
        showOnHomepage: true,
        planHighlight: true,
    },
    FEED: {
        id: 'feed',
        key: 'FEED',
        name: 'Feed',
        shortName: 'Feed',
        description: {
            short: 'Pre-scored matches from your alerts.',
            full: 'A live feed of pre-scored job matches automatically triaged from your alerts. Your best opportunities, ranked.',
            plan: 'Live feed of ranked job matches',
        },
        action: { short: 'View feed', full: 'Open Feed' },
        iconName: 'Zap',
        colorKey: 'indigo-dark',
        category: 'JOB',
        tier: 'plus',
        targetView: 'feed',
        link: '/jobs/feed',
        rank: 4,
        showOnHomepage: true,
        planHighlight: true,
    },
    MAIL_IN: {
        id: 'mail-in',
        key: 'MAIL_IN',
        name: 'Job Alerts',
        shortName: 'Inbound',
        description: {
            short: 'Forward jobs to analysis via email.',
            full: 'Forward your job board alerts to a unique Navigator email. Every listing gets analyzed and scored automatically in your feed.',
            plan: 'Auto-analyze jobs forwarded via email',
        },
        action: { short: 'View token', full: 'Set up' },
        iconName: 'Mail',
        colorKey: 'amber-dark',
        category: 'JOB',
        tier: 'plus',
        targetView: 'feed',
        link: '/jobs/feed',
        rank: 9,
        showOnHomepage: true,
        stage: 'beta',
    },
    SKILLS_INTERVIEW: {
        id: 'skills-verify',
        key: 'SKILLS_INTERVIEW',
        name: 'Skills Interview',
        shortName: 'Interview',
        description: {
            short: 'Prove your skills with AI interviews.',
            full: 'Prove your skills with a live AI-powered interview. Answer real questions, get instant feedback, and earn verified proficiency badges.',
            plan: 'AI skill verification interviews',
        },
        action: { short: 'Start', full: 'Start' },
        iconName: 'Shield',
        colorKey: 'emerald',
        category: 'COACH',
        tier: 'plus',
        targetView: 'skills',
        link: '/career/skills/interview',
        rank: 17,
    },
    INTERVIEW_ADVISOR: {
        id: 'interview-advisor',
        key: 'INTERVIEW_ADVISOR',
        name: 'Interview Advisor',
        shortName: 'Mock Interview',
        description: {
            short: 'Realistic mock interviews with scoring.',
            full: 'Practice with realistic mock interviews tailored precisely to any job. Answer adaptive questions and get scored in real time.',
            plan: 'AI-powered mock interviews with scoring',
        },
        action: { short: 'Practice', full: 'Practice' },
        iconName: 'MessageSquare',
        colorKey: 'sky',
        category: 'JOB',
        tier: 'plus',
        targetView: 'interviews',
        link: '/jobs/interviews',
        rank: 18,
        stage: 'beta',
    },
    COACH: {
        id: 'coach',
        key: 'COACH',
        name: 'Career Roadmaps',
        shortName: 'Roadmap',
        description: {
            short: 'Analyze skill gaps for any role.',
            full: 'Map your path to any role. Get a concrete, step-by-step plan to bridge the gap and land the job.',
            plan: 'Step-by-step navigation to your goal role',
        },
        action: { short: 'Scale up', full: 'Learn more' },
        iconName: 'TrendingUp',
        colorKey: 'teal',
        category: 'COACH',
        tier: 'pro',
        targetView: 'coach-home',
        link: '/career/growth',
        rank: 7,
        showOnHomepage: false,
        planHighlight: true,
    },
    ROLE_MODELS: {
        id: 'role-modeling',
        key: 'ROLE_MODELS',
        name: 'Role Modeling',
        shortName: 'Role Models',
        description: {
            short: 'Compare your path to industry leaders.',
            full: "Upload a mentor's LinkedIn profile and see a side-by-side comparison of your skills, experience, and credentials against theirs.",
            plan: 'Compare your path to industry leaders',
        },
        action: { short: 'Compare', full: 'Compare' },
        iconName: 'Users',
        colorKey: 'teal',
        category: 'COACH',
        tier: 'pro',
        targetView: 'coach-home',
        link: '/career/models',
        rank: 19,
        planHighlight: true,
    },
    EXTENSION: {
        id: 'extension',
        key: 'EXTENSION',
        name: 'Browser Extension',
        shortName: 'Extension',
        description: {
            short: 'Save jobs from any website instantly.',
            full: "Save job postings from any website with a single click. Structured data is extracted instantly — no copying and pasting.",
            plan: 'One-click job saving from any site',
        },
        action: { short: 'Install', full: 'Install' },
        iconName: 'Globe',
        colorKey: 'blue',
        category: 'JOB',
        tier: 'explorer',
        stage: 'beta',
        targetView: 'history',
        link: '/jobs',
        rank: 20,
    },
    EDU: {
        id: 'edu',
        key: 'EDU',
        name: 'Education',
        shortName: 'Edu',
        description: {
            short: 'Smart degree and credit tracking.',
            full: 'Your central hub for degree tracking and program discovery. Manage your academic journey with AI.',
            plan: 'AI-powered tools for degree & program planning',
        },
        action: { short: 'Open', full: 'Open Hub' },
        iconName: 'GraduationCap',
        colorKey: 'amber',
        category: 'EDUCATION',
        tier: 'pro',
        targetView: 'edu-home',
        link: '/education',
        rank: 8,
        showOnHomepage: false,
    },
    EDU_EXPLORER: {
        id: 'edu-explorer',
        key: 'EDU_EXPLORER',
        name: 'Programs',
        shortName: 'Programs',
        description: {
            short: "Explore master's degrees and certs.",
            full: 'Get personalized recommendations for degrees and track your current program requirements using AI.',
            plan: 'Personalized degree & certification recommendations',
        },
        action: { short: 'Explore', full: 'Explore' },
        iconName: 'School',
        colorKey: 'emerald',
        category: 'EDUCATION',
        tier: 'pro',
        targetView: 'edu-programs',
        link: '/education/programs',
        rank: 11,
        stage: 'beta',
    },
    EDU_TRANSCRIPT: {
        id: 'edu-transcript',
        key: 'EDU_TRANSCRIPT',
        name: 'Transcript',
        shortName: 'Transcript',
        releaseDate: '2025-02-23',
        description: {
            short: 'Manage coursework and monitor progress.',
            full: 'Track your coursework, credits, and degree progress in one place.',
            plan: 'Coursework and degree progress tracking',
        },
        action: { short: 'View', full: 'Open' },
        iconName: 'GraduationCap',
        colorKey: 'amber',
        category: 'EDUCATION',
        tier: 'explorer',
        targetView: 'edu-transcript',
        link: '/education/transcript',
        rank: 10,
    },
    EDU_GPA: {
        id: 'edu-gpa',
        key: 'EDU_GPA',
        name: 'GPA Calculator',
        shortName: 'GPA',
        description: {
            short: 'Calculate targets and track performance.',
            full: 'Calculate your current GPA and play out different grade scenarios. See exactly what it takes to reach your target number.',
            plan: 'GPA calculation and scenario planning',
        },
        action: { short: 'Calculate', full: 'Calculate' },
        iconName: 'Calculator',
        colorKey: 'blue',
        category: 'EDUCATION',
        tier: 'explorer',
        targetView: 'edu-gpa',
        link: '/education/gpa',
        rank: 12,
    },
    ORGS: {
        id: 'orgs',
        key: 'ORGS',
        name: 'Professional Organizations',
        shortName: 'Organizations',
        description: {
            short: 'Track your professional memberships.',
            full: 'Keep track of the professional associations, networks, and communities you belong to — all in one place.',
            plan: 'Professional organization membership tracking',
        },
        action: { short: 'View', full: 'Manage' },
        iconName: 'Building2',
        colorKey: 'teal',
        category: 'COACH',
        tier: 'explorer',
        targetView: 'career-orgs',
        link: '/career',
        rank: 21,
        stage: 'beta',
    },
    // ─── System Notices (Pseudo-features) ──────────────────────────────
    _NOTICE_ARCHETYPE: {
        id: '_notice_archetype',
        key: '_NOTICE_ARCHETYPE',
        name: 'Current Focus Update',
        shortName: 'Update Focus',
        description: {
            short: 'Recommendations work best when your focus is current.',
            full: 'It has been a few months since you updated your career focus. Review your trajectory to keep Navigator sharp.',
            plan: '',
        },
        action: { short: 'Update Now', full: 'Update' },
        iconName: 'Activity',
        colorKey: 'indigo',
        category: 'JOB',
        tier: 'explorer',
        targetView: 'settings', // Trigger settings modal
        link: '#',
        rank: 999,
        showOnHomepage: false,
    },
    _NOTICE_TOS: {
        id: '_notice_tos',
        key: '_NOTICE_TOS',
        name: 'Policy Update',
        shortName: 'Policy Update',
        description: {
            short: 'We have updated our Terms & Privacy policy.',
            full: 'Please review the latest changes to our Terms of Service and Privacy Policy to continue using Navigator.',
            plan: '',
        },
        action: { short: 'Review', full: 'Review' },
        iconName: 'Shield',
        colorKey: 'rose',
        category: 'JOB',
        tier: 'explorer',
        targetView: 'terms',
        link: '/terms',
        rank: 999,
        showOnHomepage: false,
    },
} as const;
